name: 'Build and Package Angular'
description: 'Builds the Angular project and moves the compressed zip to the output directory'

inputs:
  Node-version:
    description: 'Node version to use'
    required: false
    default: '22.19.0'
  app-name:
    description: 'The Angular app name to build and package'
    required: false

outputs:
  artifact_name:
    description: 'The name of the uploaded artifact'
    value: ${{ steps.set-artifact-name.outputs.artifact_name }}

runs:
  using: 'composite'
  steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.Node-version }}
        cache: 'npm'
    
    - name: Install Requirements
      shell: bash
      run: npm ci
    
    - name: Build
      shell: bash
      run: npx ng build --configuration production --output-hashing=all

    - name: Compression          
      shell: bash
      run: zip -r -q AngularFiles.zip ./dist/*
    
    - name: Set artifact name output
      id: set-artifact-name
      shell: bash
      run: echo "artifact_name=CompiledF" >> $GITHUB_OUTPUT

    - name: Upload Angular ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: CompiledF
        path: AngularFiles.zip

