name: 'Deploy artifact to VM'
description: 'Pushes Built artifact to the Deployment Directory'

inputs:
  artifactName:
    required: false
    default: "CompiledF"
  deploymentFolder:
    required: false
  executionRequired:
    required: false
    default: "false"
  serviceLanguage:
    required: false

### Secrets as inputs ###
  SSH_HOST:
    required: false
  SSH_PRIVATE_KEY:
    required: false
  SSH_USER:
    required: false

run:
  using: 'composite'
  steps:
    - name: Set up SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.SSH_PRIVATE_KEY }}

    - name: Add host to known_hosts
      shell: bash
      run: ssh-keyscan -H ${{ inputs.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifactName }}
        path: ./artifact

    - name: Deploy
      shell: bash
      run: |
        scp -r ./artifact/* ${{ inputs.SSH_USER }}@${{ inputs.SSH_HOST }}:${{ inputs.deploymentFolder }}/

    - name: SpringBoot Execution
      if: inputs.executionRequired == 'true' && (inputs.serviceLanguage == 'SpringBoot' || inputs.serviceLanguage == 'Java')
      shell: bash
      run: |
        ssh ${{ inputs.SSH_USER }}@${{ inputs.SSH_HOST }} bash << 'EOF'
          cd ${{ inputs.deploymentFolder }}
          pkill -f 'java -jar' || true
          JAR_FILE=$(ls -t *.jar | head -1)
          nohup java -jar "$JAR_FILE" > app.log 2>&1 &
          for i in {1..10}; do
            pgrep -f 'java -jar' && echo "App started successfully" && exit 0
            echo "Waiting... attempt $i"
            sleep 3
          done
          echo "JAR failed to start, check app.log"
          exit 1
        EOF