name: Application CI

on:
  push:
    branches: [ main, UAT, staging ]

jobs:
  security_check:
    name: Run Security Pipeline
    # Ensure this path matches the physical location of the reusable workflow
    uses: SathyaNarayana-indsys/studious-octo-meme/.github/workflows/AWS-VM-Deployment.yml@main
    with:
      environment: ${{ github.ref_name }} 
      BuildRequried: 'False'
      deploymentFolder: ${{ vars.DEPLOYMENT_FOLDER }}
      executionRequired: 'true'
      executionType: 'ServiceRestart'
      ServiceLanguage: 'Python'
      ServiceDefFile: ''
      serviceLanguageVersion: '3.14' #optional Here
      ScriptExecution: "True"
      ServiceRestart: "True"
      ServiceName: ""
      runScript: ""
      # break_on_failure: "False"
      serviceVersion: ${{ github.sha }}

    secrets: inherit
