name: Application CI

on:
  push:
    branches: [ main, UAT, staging ]

jobs:
  security_check:
    name: Run Security Pipeline
    # Ensure this path matches the physical location of the reusable workflow
    uses: SathyaNarayana-indsys/studious-octo-meme/.github/workflows/AWS-VM-Deployment.yml@main
    with:
      # Mapping the GitHub branch to the 'environment' input
      environment: ${{ github.ref_name }} 
      BuildRequried: 'True'
      serviceLanguage: 'SpringBoot'
      serviceLanguageVersion: ''
      deploymentFolder: ${{ vars.DEPLOYMENT_FOLDER }}
      executionRequired: 'true'
      runScript: ${{ vars.RUN_SCRIPT }}
      break_on_failure: "False"
      serviceVersion: ${{ github.sha }}

    secrets: inherit