name: Application CI
on:
  push:
    branches: [ main ]

jobs:
  security_check:
    name: Run Security Pipeline
    runs-on: ubuntu-latest
    
    # This step calls your reusable workflow
    uses: SathyaNarayana-indsys/studious-octo-meme/.github/workflows/Security Pipeline.yml
    
    with:
      # Pass the inputs from the calling workflow or set default values
      deployment_type: ${{ github.event.inputs.deployment_type }}
      BuildScript: ${{ github.event.inputs.BuildScript }}
      DryRun: ${{ github.event.inputs.DryRun }}
      break_on_failure: ${{ github.event.inputs.break_on_failure }}
      
    secrets:
      # Pass required secrets to the reusable workflow
      REPORTS_REPO_PAT: ${{ secrets.REPORTS_REPO_PAT }}
      USER: ${{ secrets.VM_USER }}
      HOST: ${{ secrets.VM_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_KEY }}