name: Application CI
on:
  push:
    branches: [ main ]

jobs:
  security_check:
    name: Run Security Pipeline
    uses: SathyaNarayana-indsys/studious-octo-meme/.github/workflows/Secure-Main.yml@main
    with:
      deployment_type: VM #either VM or Container defaults to VM
      deploymentFolder: ${{ vars.folder }} #the desired folder for deployment
      envType: 'AWS' #AWS or GCP or OnPrem Location
      executionRequired: 'true'
      runscript: ${{ vars.script }}
      # break_on_failure: false # Required for deployment logic, set to false for emergency bypass
      # DryRun: false

    secrets: inherit
