name: Application CI
on:
  push:
    branches: [ main ]

jobs:
  security_check:
    name: Run Security Pipeline
    uses: <Your-Org>/<Your-Template-Repo>/.github/workflows/security-pipeline.yml@main
    with:
      # Required for deployment logic, set to false for emergency bypass
      break_on_failure: true 
      language: Python
      languageVersion: '3.10'
      deployment_type: VM
      # Variable that holds the reports repo link (e.g., 'your-org/security-reports')
      repo_link: ${{ vars.REPORTS_REPO_NAME }} 
    secrets:
      REPORTS_REPO_PAT: ${{ secrets.REPORTS_REPO_PAT }}
      USER: ${{ secrets.SSH_USER }}
      HOST: ${{ secrets.SSH_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}