name: Application CI

on:
  push:
    branches: [ main, UAT, staging ]

jobs:
  security_check:
    name: Run Security Pipeline
    uses: SathyaNarayana-indsys/studious-octo-meme/.github/workflows/AWS-VM-Deployment.yml@main
    with:
      environment: 'main'
      deployment_type: 'VM'
      BuildRequried: 'True'
      BuildLanguage: 'SpringBoot'
      deploymentFolder: ${{ vars.DEPLOYMENT_FOLDER }}
      envType: 'AWS'
      envRegion: 'ap-south-1'
      executionRequired: 'true'
      runScript: ${{ vars.RUN_SCRIPT }}
      break_on_failure: "False"      # Uncomment for emergency bypass
      # DryRun: 'True'               # Uncomment to test without deploying

    secrets: inherit
