name: 'Deploy to VM'
description: 'Builds the Maven project and moves the JAR to the output directory'

inputs:
  repoUser:
    required: false
    type: string
    default: "ssm-user"
  runScript:
    required: false
    type: string
  deploymentFolder:
    required: false
    type: string
  executionRequired:
    required: false
    type: boolean
    default: false
  environmentName:
    required: false
    type: string
    default: main
  envType:
    required: false
    type: string
    default: "AWS"
  envRegion:
    required: false
    type: string
    default: "ap-south-1"

### Secrets as inputs ###
  AWS_ACCESS_KEY_ID:
    required: false
    type: string
  AWS_SECRET_ACCESS_KEY:
    required: false
    type: string
  INSTANCE_ID:
    required: false
    type: string
  SSH_PRIVATE_KEY:
    required: false
    type: string
  SSH_HOSTNAME:
    required: false
    type: string
  SSH_USER:
    required: false
    type: string